// PartiuAlmoco/PartiuAlmoco.Web.Client/ClientApp/src/app/nav-menu/nav-menu.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { User } from '../interfaces/user';
import { AuthenticationService } from '../services/authentication.service';

@Component({
  selector: 'app-nav-menu',
  templateUrl: './nav-menu.component.html',
  styleUrls: ['./nav-menu.component.css']
})
export class NavMenuComponent implements OnInit {
  constructor(private authentication: AuthenticationService, private router: Router) { }

  ngOnInit() {
    this.authentication.authenticationChanged.subscribe((user) => {
      this.currentUser = user;
      this.isAuthenticated = user != null;
    });
  }

  isExpanded = false;

  isAuthenticated = false;
  currentUser: User = null;

  collapse() {
    this.isExpanded = false;
  }

  toggle() {
    this.isExpanded = !this.isExpanded;
  }

  logout() {
    this.authentication.logout();
    this.router.navigate(["/"]);
    return false;
  }
}

<header>
  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
      <a class="navbar-brand" [routerLink]="['/']"><strong>Partiu Almoço!</strong></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
        aria-label="Toggle navigation" [attr.aria-expanded]="isExpanded" (click)="toggle()">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" [ngClass]="{ show: isExpanded }">
        <ul class="navbar-nav flex-grow">
          <li class="nav-item"><a class="text-dark nav-link" [routerLinkActive]="['link-active']" [routerLink]="['/votacao']">Votação</a></li>
          <li *ngIf="isAuthenticated" class="nav-item"><a class="text-dark nav-link" [routerLinkActive]="['link-active']" [routerLink]="['/restaurantes']">Restaurantes</a></li>
          <!-- <li class="nav-item"><a class="text-dark nav-link" href="/historico">Histórico</a></li> -->
          <li *ngIf="!isAuthenticated" class="nav-item"><a class="text-dark nav-link" [routerLinkActive]="['link-active']" [routerLink]="['/entrar']">Entrar</a></li>
          <li *ngIf="isAuthenticated" class="nav-item"><a class="text-dark nav-link" [routerLinkActive]="['link-active']" href="#" (click)="logout()">Sair</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

// PartiuAlmoco/PartiuAlmoco.Web.Client/ClientApp/src/components/NavMenu.tsx
﻿import * as React from 'react';
import { Collapse, Container, Navbar, NavbarBrand, NavbarToggler, NavItem, NavLink } from 'reactstrap';
import { Link } from 'react-router-dom';
import './NavMenu.css';

export default class NavMenu extends React.PureComponent<{}, { isOpen: boolean }> {
    public state = {
        isOpen: false
    };

    public render() {
        return (
            <header>
                <Navbar className="navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" light>
                    <Container>
                        <NavbarBrand tag={Link} to="/"><strong>Partiu Almoço!</strong></NavbarBrand>
                        <NavbarToggler onClick={this.toggle} className="mr-2"/>
                        <Collapse className="d-sm-inline-flex flex-sm-row-reverse" isOpen={this.state.isOpen} navbar>
                            <ul className="navbar-nav flex-grow">
                                <NavItem>
                                    <NavLink tag={Link} className="text-dark" to="/">Restaurantes</NavLink>
                                </NavItem>
                                <NavItem>
                                    <NavLink tag={Link} className="text-dark" to="/votacao">Votação</NavLink>
                                </NavItem>
                                <NavItem>
                                    <NavLink tag={Link} className="text-dark" to="/fetch-data">Entrar</NavLink>
                                </NavItem>
                            </ul>
                        </Collapse>
                    </Container>
                </Navbar>
            </header>
        );
    }

    private toggle = () => {
        this.setState({
            isOpen: !this.state.isOpen
        });
    }
}
